version: v2.39.2-desktop.1

# Перечень volume
volumes:
  pg_data:
  # Новый volume — для статических файлов
  static:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    container_name: db
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - django-network
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: ./backend/
    container_name: backend
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    networks:
      - django-network
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    build: ./frontend/
    container_name: frontend
    networks:
      - django-network
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
# Добавляем новый контейнер: gateway
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
    container_name: gateway
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    networks:
      - django-network

networks:
  django-network:
